In [1]:
import pandas as pd
import warnings
from IPython.utils import io
import sys
import numpy as np
from functools import reduce

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

stars_dir = '~/GitHub/stars-data-builder/'
hos_dir = '~/Desktop/Rush/CMS_HospitalArchives/'

# 
----

# Compare derived input files for 2024 to each other and to the actual input file released by CMS

Load derived input data files

In [2]:
jul_df = pd.read_csv(stars_dir + "Reproduce_Stars_Input/2024/Input_File/data_for_2024_prognostications_from_Jul2023.csv")
ls = []
for p in jul_df['PROVIDER_ID'].tolist():
    p = int(p)
    p = str(p)
    if '666666' in p:
        p = p[:-6]
        p = p + 'F'
    while len(p) < 6:
        p = '0' + p
    ls.append(p)

jul_df['PROVIDER_ID'] = ls


oct_df = pd.read_csv(stars_dir + "Reproduce_Stars_Input/2024/Input_File/data_for_2024_prognostications_from_Oct2023.csv")
ls = []
for p in oct_df['PROVIDER_ID'].tolist():
    p = int(p)
    p = str(p)
    if '666666' in p:
        p = p[:-6]
        p = p + 'F'
    while len(p) < 6:
        p = '0' + p
    ls.append(p)

oct_df['PROVIDER_ID'] = ls


nov_df = pd.read_csv(stars_dir + "Reproduce_Stars_Input/2024/Input_File/data_for_2024_prognostications_from_Nov2023.csv")
ls = []
for p in nov_df['PROVIDER_ID'].tolist():
    p = int(p)
    p = str(p)
    if '666666' in p:
        p = p[:-6]
        p = p + 'F'
    while len(p) < 6:
        p = '0' + p
    ls.append(p)

nov_df['PROVIDER_ID'] = ls


jan_df = pd.read_csv(stars_dir + "Reproduce_Stars_Input/2024/Input_File/data_for_2024_prognostications_from_Jan2024.csv")
ls = []
for p in jan_df['PROVIDER_ID'].tolist():
    p = int(p)
    p = str(p)
    if '666666' in p:
        p = p[:-6]
        p = p + 'F'
    while len(p) < 6:
        p = '0' + p
    ls.append(p)

jan_df['PROVIDER_ID'] = ls


jan_df.head()

,PROVIDER_ID,HAI_1_DEN_VOL,HAI_2_DEN_VOL,HAI_3_DEN_VOL,HAI_4_DEN_VOL,HAI_5_DEN_VOL,HAI_6_DEN_VOL,HAI_1_DEN_PRED,HAI_2_DEN_PRED,HAI_3_DEN_PRED,HAI_4_DEN_PRED,HAI_5_DEN_PRED,HAI_6_DEN_PRED,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,READM_30_HOSP_WIDE_DEN,READM_30_HIP_KNEE_DEN,EDAC_30_HF_DEN,READM_30_COPD_DEN,EDAC_30_AMI_DEN,EDAC_30_PN_DEN,MORT_30_STK_DEN,MORT_30_PN_DEN,MORT_30_HF_DEN,MORT_30_COPD_DEN,MORT_30_AMI_DEN,COMP_HIP_KNEE_DEN,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_8,OP_8_DEN,OP_10,OP_10_DEN,OP_13,OP_13_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,PSI_90_SAFETY,IMM_3_DEN,IMM_3,HCP_COVID_19_DEN,HCP_COVID_19,PC_01,PC_01_DEN,SEP_1,SEP_1_DEN,H_RESP_RATE_P,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,H_NUMB_COMP,PSI_90_SAFETY_DEN,MORT_30_CABG,MORT_30_CABG_DEN,READM_30_CABG,READM_30_CABG_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN
0,010001,9149.0,17310.0,214.0,76.0,104733.0,104733.0,9.597,24.766,5.994,0.712,11.400,67.066,0.938,0.363,1.335,NaN,0.965,0.507,0.142,0.038,23.4,0.190,-15.4,23.6,0.148,0.180,0.089,0.088,0.120,0.027,2912.0,49.0,614.0,117.0,274.0,403.0,398.0,400.0,549.0,107.0,278.0,49.0,NaN,NaN,NaN,NaN,0.380,NaN,0.061,NaN,0.028,NaN,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,184.68,134.0,1.21,3905.0,0.95,NaN,0.836,0.00,32.0,0.65,127.0,15.0,3.0,3.0,3.0,3.0,4.0,4.0,3.5,3.5,544.0,NaN,0.041,132.0,0.105,126.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0
1,010005,3194.0,8277.0,96.0,34.0,36794.0,34887.0,1.989,4.019,2.626,0.324,1.847,10.066,2.514,0.995,0.762,NaN,0.541,0.497,0.128,0.034,22.1,0.166,NaN,-6.2,0.153,0.233,0.149,0.099,0.136,0.023,1052.0,172.0,129.0,136.0,NaN,285.0,81.0,289.0,121.0,126.0,27.0,155.0,NaN,NaN,57.0,16.0,0.477,NaN,0.120,NaN,0.042,NaN,145.0,1074.0,0.03,56820.0,0.58,12.0,0.96,180.0,183.49,43.0,0.97,2700.0,0.80,NaN,0.807,0.02,200.0,0.69,252.0,18.0,3.0,4.0,1.0,3.0,4.0,3.0,3.0,3.0,824.0,NaN,NaN,NaN,NaN,NaN,14.2,739.0,7.9,107.0,5.5,107.0,1.9,406.0
2,010006,5343.0,8715.0,111.0,14.0,63727.0,60304.0,5.801,11.166,2.950,0.124,5.283,27.805,0.172,0.358,0.000,NaN,1.514,0.072,0.134,0.053,-4.7,0.176,28.1,-0.4,0.172,0.195,0.125,0.099,0.165,0.046,2310.0,138.0,441.0,158.0,273.0,472.0,227.0,469.0,388.0,148.0,254.0,145.0,NaN,NaN,NaN,NaN,0.462,NaN,0.101,NaN,0.045,NaN,168.0,360.0,0.01,42286.0,0.75,16.0,0.85,82.0,173.63,96.0,1.17,2536.0,0.67,NaN,0.796,0.04,28.0,0.57,126.0,19.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.5,1503.0,NaN,0.036,95.0,0.124,89.0,12.1,1355.0,NaN,NaN,NaN,NaN,1.4,484.0
3,010007,343.0,1193.0,3.0,NaN,5511.0,5511.0,0.210,0.652,0.089,NaN,0.133,2.660,NaN,NaN,NaN,NaN,NaN,0.376,0.157,0.042,-1.9,0.200,NaN,-9.4,NaN,0.285,0.125,0.137,NaN,NaN,258.0,26.0,31.0,34.0,NaN,72.0,NaN,88.0,26.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.034,NaN,NaN,NaN,132.0,1275.0,0.04,11202.0,NaN,NaN,0.23,111.0,NaN,NaN,0.95,350.0,0.53,NaN,0.601,NaN,NaN,0.93,43.0,24.0,3.0,5.0,4.0,3.0,3.0,3.0,3.5,3.0,189.0,NaN,NaN,NaN,NaN,NaN,13.4,109.0,NaN,NaN,NaN,NaN,1.2,59.0
4,010008,41.0,444.0,NaN,NaN,2376.0,2376.0,0.023,0.242,NaN,NaN,0.055,0.436,NaN,NaN,NaN,NaN,NaN,NaN,0.148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,NaN,116.0,340.0,0.00,6239.0,NaN,NaN,0.67,24.0,NaN,NaN,NaN,126.0,0.45,NaN,0.797,NaN,NaN,NaN,NaN,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,12.9,42.0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
with io.capture_output() as captured: 
    df_2024 = pd.read_sas(stars_dir + '2024/2024-07 Stars Release/alldata_2024jul.sas7bdat')
df_2024 = df_2024.applymap(lambda x: x.decode() if isinstance(x, bytes) else x)

print(df_2024.shape)
prvdrs = df_2024['PROVIDER_ID'].unique()
print(len(prvdrs), 'hospitals in 2024')

df_2024.head()

(4658, 95)
4658 hospitals in 2024

,PROVIDER_ID,HAI_1_DEN_VOL,HAI_2_DEN_VOL,HAI_3_DEN_VOL,HAI_4_DEN_VOL,HAI_5_DEN_VOL,HAI_6_DEN_VOL,HAI_1_DEN_PRED,HAI_2_DEN_PRED,HAI_3_DEN_PRED,HAI_4_DEN_PRED,HAI_5_DEN_PRED,HAI_6_DEN_PRED,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,READM_30_HOSP_WIDE_DEN,READM_30_HIP_KNEE_DEN,EDAC_30_HF_DEN,READM_30_COPD_DEN,EDAC_30_AMI_DEN,EDAC_30_PN_DEN,MORT_30_STK_DEN,MORT_30_PN_DEN,MORT_30_HF_DEN,MORT_30_COPD_DEN,MORT_30_AMI_DEN,COMP_HIP_KNEE_DEN,OP_2,OP_2_DEN,OP_3B,OP_3B_DEN,OP_8,OP_8_DEN,OP_10,OP_10_DEN,OP_13,OP_13_DEN,OP_18B,OP_18B_DEN,OP_22,OP_22_DEN,OP_23,OP_23_DEN,OP_29,OP_29_DEN,PSI_4_SURG_COMP,PSI_4_SURG_COMP_DEN,PSI_90_SAFETY,IMM_3_DEN,IMM_3,HCP_COVID_19_DEN,HCP_COVID_19,PC_01,PC_01_DEN,SEP_1,SEP_1_DEN,H_RESP_RATE_P,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,H_NUMB_COMP,PSI_90_SAFETY_DEN,MORT_30_CABG,MORT_30_CABG_DEN,READM_30_CABG,READM_30_CABG_DEN,OP_32,OP_32_DEN,OP_35_ADM,OP_35_ADM_DEN,OP_35_ED,OP_35_ED_DEN,OP_36,OP_36_DEN
0,010001,9149.0,17310.0,214.0,NaN,104733.0,104733.0,9.597,24.766,5.994,NaN,11.400,67.066,0.938,0.363,1.335,NaN,0.965,0.507,0.142,0.038,23.4,0.190,-15.4,23.6,0.148,0.180,0.089,0.088,0.120,0.027,2912.0,49.0,614.0,117.0,274.0,403.0,398.0,400.0,549.0,107.0,278.0,49.0,NaN,NaN,NaN,NaN,0.380,79.0,0.061,1410.0,0.028,178.0,214.0,348.0,0.05,52960.0,NaN,NaN,0.47,17.0,184.68,134.0,1.21,3905.0,0.95,2496.0,0.836,0.00,32.0,0.65,127.0,15.0,3.0,3.0,3.0,3.0,4.0,4.0,3.5,3.5,544.0,2542.038500,0.041,132.0,0.105,126.0,12.9,170.0,11.9,202.0,4.9,202.0,1.1,668.0
1,010005,3194.0,8277.0,96.0,NaN,36794.0,34887.0,1.989,4.019,2.626,NaN,1.847,10.066,2.514,0.995,0.762,NaN,0.541,0.497,0.128,0.034,22.1,0.166,NaN,-6.2,0.153,0.233,0.149,0.099,0.136,0.023,1052.0,172.0,129.0,136.0,NaN,285.0,81.0,289.0,121.0,126.0,27.0,155.0,NaN,NaN,57.0,16.0,0.477,130.0,0.120,1057.0,0.042,189.0,145.0,1074.0,0.03,56820.0,0.58,12.0,0.96,180.0,183.49,43.0,0.97,2700.0,0.80,2552.0,0.807,0.02,200.0,0.69,252.0,18.0,3.0,4.0,1.0,3.0,4.0,3.0,3.0,3.0,824.0,978.028994,NaN,NaN,NaN,NaN,14.2,739.0,7.9,107.0,5.5,107.0,1.9,406.0
2,010006,5343.0,8715.0,111.0,NaN,63727.0,60304.0,5.801,11.166,2.950,NaN,5.283,27.805,0.172,0.358,0.000,NaN,1.514,0.072,0.134,0.053,-4.7,0.176,28.1,-0.4,0.172,0.195,0.125,0.099,0.165,0.046,2310.0,138.0,441.0,158.0,273.0,472.0,227.0,469.0,388.0,148.0,254.0,145.0,NaN,NaN,NaN,NaN,0.462,39.0,0.101,978.0,0.045,221.0,168.0,360.0,0.01,42286.0,0.75,16.0,0.85,82.0,173.63,96.0,1.17,2536.0,0.67,1882.0,0.796,0.04,28.0,0.57,126.0,19.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.5,1503.0,1753.979899,0.036,95.0,0.124,89.0,12.1,1355.0,NaN,NaN,NaN,NaN,1.4,484.0
3,010007,NaN,NaN,NaN,NaN,NaN,5511.0,NaN,NaN,NaN,NaN,NaN,2.660,NaN,NaN,NaN,NaN,NaN,0.376,0.157,0.042,-1.9,0.200,NaN,-9.4,NaN,0.285,0.125,0.137,NaN,NaN,258.0,26.0,31.0,34.0,NaN,72.0,NaN,88.0,26.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.034,146.0,NaN,NaN,132.0,1275.0,0.04,11202.0,NaN,NaN,0.23,111.0,NaN,NaN,0.95,350.0,0.53,252.0,0.601,NaN,NaN,0.93,43.0,24.0,3.0,5.0,4.0,3.0,3.0,3.0,3.5,3.0,189.0,228.286193,NaN,NaN,NaN,NaN,13.4,109.0,NaN,NaN,NaN,NaN,1.2,59.0
4,010008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,85.0,NaN,NaN,116.0,340.0,0.00,6239.0,NaN,NaN,0.67,24.0,NaN,NaN,NaN,126.0,0.45,163.0,0.797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9,42.0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
jul_prvdrs = jul_df['PROVIDER_ID'].unique().tolist()
oct_prvdrs = oct_df['PROVIDER_ID'].unique().tolist()
nov_prvdrs = nov_df['PROVIDER_ID'].unique().tolist()
jan_prvdrs = jan_df['PROVIDER_ID'].unique().tolist()
act_prvdrs = df_2024['PROVIDER_ID'].unique().tolist()

lsts = [jul_prvdrs, oct_prvdrs, nov_prvdrs, jan_prvdrs, act_prvdrs]
for ls in lsts: print(len(ls))
print('\n')

sets = [set(ls) for ls in lsts]
common_prvdrs = list(sets[0].intersection(*sets[1:]))

print(len(common_prvdrs))

4606
4678
4673
4654
4658


4604

In [5]:
df_2024 = df_2024[df_2024['PROVIDER_ID'].isin(common_prvdrs)]

jul_df = jul_df[jul_df['PROVIDER_ID'].isin(common_prvdrs)]
oct_df = oct_df[oct_df['PROVIDER_ID'].isin(common_prvdrs)]
nov_df = nov_df[nov_df['PROVIDER_ID'].isin(common_prvdrs)]
jan_df = jan_df[jan_df['PROVIDER_ID'].isin(common_prvdrs)]

jul_df.sort_values(by='PROVIDER_ID', ascending=True, inplace=True)
oct_df.sort_values(by='PROVIDER_ID', ascending=True, inplace=True)
nov_df.sort_values(by='PROVIDER_ID', ascending=True, inplace=True)
jan_df.sort_values(by='PROVIDER_ID', ascending=True, inplace=True)
df_2024.sort_values(by='PROVIDER_ID', ascending=True, inplace=True)

print(jul_df.shape)
print(oct_df.shape)
print(nov_df.shape)
print(jan_df.shape)
print(df_2024.shape)

(4604, 95)
(4604, 95)
(4604, 95)
(4604, 95)
(4604, 95)

In [6]:
strs = ['^(?!.*_DEN$).*', '^(?!.*_VOL$).*',
        '^(?!.*_DEN_).*$', '^(?!.*_NUMB_).*$',
        '^(?!OP_2$).*', '^(?!H_RESP_RATE_P$).*']

for st in strs:
    df_2024 = df_2024.filter(regex=st)
    jul_df = jul_df.filter(regex=st)
    oct_df = oct_df.filter(regex=st)
    nov_df = nov_df.filter(regex=st)
    jan_df = jan_df.filter(regex=st)

print(jul_df.shape)
print(oct_df.shape)
print(nov_df.shape)
print(jan_df.shape)
print(df_2024.shape)

jul_df.reset_index(drop=True, inplace=True)
oct_df.reset_index(drop=True, inplace=True)
nov_df.reset_index(drop=True, inplace=True)
jan_df.reset_index(drop=True, inplace=True)
df_2024.reset_index(drop=True, inplace=True)

(4604, 47)
(4604, 47)
(4604, 47)
(4604, 47)
(4604, 47)

In [7]:
df_2024.head()

,PROVIDER_ID,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,OP_3B,OP_8,OP_10,OP_13,OP_18B,OP_22,OP_23,OP_29,PSI_4_SURG_COMP,PSI_90_SAFETY,IMM_3,HCP_COVID_19,PC_01,SEP_1,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,MORT_30_CABG,READM_30_CABG,OP_32,OP_35_ADM,OP_35_ED,OP_36
0,010001,0.938,0.363,1.335,NaN,0.965,0.507,0.142,0.038,23.4,0.190,-15.4,23.6,0.148,0.180,0.089,0.088,0.120,0.027,NaN,0.380,0.061,0.028,214.0,0.05,NaN,0.47,184.68,1.21,0.95,0.836,0.00,0.65,3.0,3.0,3.0,3.0,4.0,4.0,3.5,3.5,0.041,0.105,12.9,11.9,4.9,1.1
1,010005,2.514,0.995,0.762,NaN,0.541,0.497,0.128,0.034,22.1,0.166,NaN,-6.2,0.153,0.233,0.149,0.099,0.136,0.023,57.0,0.477,0.120,0.042,145.0,0.03,0.58,0.96,183.49,0.97,0.80,0.807,0.02,0.69,3.0,4.0,1.0,3.0,4.0,3.0,3.0,3.0,NaN,NaN,14.2,7.9,5.5,1.9
2,010006,0.172,0.358,0.000,NaN,1.514,0.072,0.134,0.053,-4.7,0.176,28.1,-0.4,0.172,0.195,0.125,0.099,0.165,0.046,NaN,0.462,0.101,0.045,168.0,0.01,0.75,0.85,173.63,1.17,0.67,0.796,0.04,0.57,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.5,0.036,0.124,12.1,NaN,NaN,1.4
3,010007,NaN,NaN,NaN,NaN,NaN,0.376,0.157,0.042,-1.9,0.200,NaN,-9.4,NaN,0.285,0.125,0.137,NaN,NaN,NaN,NaN,0.034,NaN,132.0,0.04,NaN,0.23,NaN,0.95,0.53,0.601,NaN,0.93,3.0,5.0,4.0,3.0,3.0,3.0,3.5,3.0,NaN,NaN,13.4,NaN,NaN,1.2
4,010008,NaN,NaN,NaN,NaN,NaN,NaN,0.148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,116.0,0.00,NaN,0.67,NaN,NaN,0.45,0.797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9,NaN,NaN,NaN

In [15]:
jul_dates = pd.read_csv(stars_dir + "2024/measure_dates/2023_07_measure_dates.csv")
oct_dates = pd.read_csv(stars_dir + "2024/measure_dates/2023_10_measure_dates.csv")
nov_dates = pd.read_csv(stars_dir + "2024/measure_dates/2023_11_measure_dates.csv")
jan_dates = pd.read_csv(stars_dir + "2024/measure_dates/2024_01_measure_dates.csv")

actual_dates = jan_dates.copy(deep=True)
jan_dates.head(jan_dates.shape[0])

                  Measure ID  Start Date    End Date
0                 HAI_1_DOPC  04/01/2022  03/31/2023
1            HAI_1_ELIGCASES  04/01/2022  03/31/2023
2                  HAI_1_SIR  04/01/2022  03/31/2023
3                 HAI_2_DOPC  04/01/2022  03/31/2023
4            HAI_2_ELIGCASES  04/01/2022  03/31/2023
5                  HAI_2_SIR  04/01/2022  03/31/2023
6                 HAI_3_DOPC  04/01/2022  03/31/2023
7            HAI_3_ELIGCASES  04/01/2022  03/31/2023
8                  HAI_3_SIR  04/01/2022  03/31/2023
9                 HAI_4_DOPC  04/01/2022  03/31/2023
10           HAI_4_ELIGCASES  04/01/2022  03/31/2023
11                 HAI_4_SIR  04/01/2022  03/31/2023
12                HAI_5_DOPC  04/01/2022  03/31/2023
13           HAI_5_ELIGCASES  04/01/2022  03/31/2023
14                 HAI_5_SIR  04/01/2022  03/31/2023
15                HAI_6_DOPC  04/01/2022  03/31/2023
16           HAI_6_ELIGCASES  04/01/2022  03/31/2023
17                 HAI_6_SIR  04/01/2022  03/31/2023
18               EDAC_30_AMI  07/01/2019  06/30/2022
19                EDAC_30_HF  07/01/2019  06/30/2022
20                EDAC_30_PN  07/01/2019  06/30/2022
21                     OP_32  01/01/2020  12/31/2022
22                 OP_35_ADM  01/01/2022  12/31/2022
23                  OP_35_ED  01/01/2022  12/31/2022
24                     OP_36  01/01/2022  12/31/2022
25             READM_30_CABG  07/01/2019  06/30/2022
26             READM_30_COPD  07/01/2019  06/30/2022
27         READM_30_HIP_KNEE  07/01/2019  06/30/2022
28        READM_30_HOSP_WIDE  07/01/2021  06/30/2022
29             COMP_HIP_KNEE  04/01/2019  03/31/2022
30               MORT_30_AMI  07/01/2019  06/30/2022
31              MORT_30_CABG  07/01/2019  06/30/2022
32              MORT_30_COPD  07/01/2019  06/30/2022
33                MORT_30_HF  07/01/2019  06/30/2022
34                MORT_30_PN  07/01/2019  06/30/2022
35               MORT_30_STK  07/01/2019  06/30/2022
36                    PSI_04  07/01/2020  06/30/2022
37                    PSI_90  07/01/2020  06/30/2022
38              HCP_COVID_19  01/01/2023  03/31/2023
39                     IMM_3  10/01/2022  03/31/2023
40                    OP_18b  04/01/2022  03/31/2023
41                      OP_2  04/01/2022  03/31/2023
42                     OP_22  01/01/2022  12/31/2022
43                     OP_23  04/01/2022  03/31/2023
44                     OP_29  01/01/2022  12/31/2022
45                     OP_3b  04/01/2022  03/31/2023
46                     SEP_1  04/01/2022  03/31/2023
47                     PC_01  04/01/2022  03/31/2023
48      H_COMP_1_STAR_RATING  04/01/2022  03/31/2023
49      H_COMP_2_STAR_RATING  04/01/2022  03/31/2023
50      H_COMP_3_STAR_RATING  04/01/2022  03/31/2023
51      H_COMP_5_STAR_RATING  04/01/2022  03/31/2023
52      H_COMP_6_STAR_RATING  04/01/2022  03/31/2023
53      H_COMP_7_STAR_RATING  04/01/2022  03/31/2023
54       H_CLEAN_STAR_RATING  04/01/2022  03/31/2023
55       H_QUIET_STAR_RATING  04/01/2022  03/31/2023
56  H_HSP_RATING_STAR_RATING  04/01/2022  03/31/2023
57      H_RECMND_STAR_RATING  04/01/2022  03/31/2023
58                     OP-10  07/01/2021  06/30/2022
59                     OP-13  07/01/2021  06/30/2022
60                      OP-8  07/01/2021  06/30/2022

In [16]:
def smape(A, F):
    with np.errstate(divide='ignore', invalid='ignore'):
        tmp = 2 * np.abs(F-A) / (np.abs(A) + np.abs(F))
    tmp[np.isnan(tmp)] = 0
    return np.sum(tmp) / len(tmp) * 100


def compare_dfs(exp_df, obs_df, mo_yr, exp_dates, obs_dates):
    
    print(mo_yr)
    
    for lab in list(exp_df):
        if lab == 'PROVIDER_ID':
            continue
        
        else:
            # Perform Comparisons
            
            # 0. Dates
            
            
            
            # 1. print no. of NaNs (obs vs exp)
            nans_exp = exp_df[lab].isna().sum()
            nans_obs = obs_df[lab].isna().sum()
            print(f'Number of NaNs in observed ({lab}): {nans_obs}')
            print(f'Number of NaNs in expected ({lab}): {nans_exp}')
            
            # 2. Print SMAPE
            # Drop NaNs for the difference calculation
            valid_exp = exp_df[lab].dropna()
            valid_obs = obs_df[lab].dropna()
            common_index = valid_exp.index.intersection(valid_obs.index)
            valid_exp = valid_exp.loc[common_index]
            valid_obs = valid_obs.loc[common_index]
            
            if valid_exp.empty or valid_obs.empty:
                print(f'No valid data to compare for {lab}')
                print('\n')
                continue
            
            # Calculate SMAPE
            smape_value = smape(valid_exp, valid_obs)
            
            print(f'Symmetric Mean Absolute Percentage Error (SMAPE) for {lab}: {smape_value:.2f}%')
            
            
            print('\n')

In [17]:
compare_dfs(df_2024, jul_df, 'July 2023', jul_dates, actual_dates)

July 2023
Number of NaNs in observed (HAI_1): 2500
Number of NaNs in expected (HAI_1): 2591
Symmetric Mean Absolute Percentage Error (SMAPE) for HAI_1: 57.06%


Number of NaNs in observed (HAI_2): 2265
Number of NaNs in expected (HAI_2): 2322
Symmetric Mean Absolute Percentage Error (SMAPE) for HAI_2: 55.88%


Number of NaNs in observed (HAI_3): 2797
Number of NaNs in expected (HAI_3): 2799
Symmetric Mean Absolute Percentage Error (SMAPE) for HAI_3: 55.13%


Number of NaNs in observed (HAI_4): 3969
Number of NaNs in expected (HAI_4): 3950
Symmetric Mean Absolute Percentage Error (SMAPE) for HAI_4: 60.93%


Number of NaNs in observed (HAI_5): 2846
Number of NaNs in expected (HAI_5): 2865
Symmetric Mean Absolute Percentage Error (SMAPE) for HAI_5: 60.39%


Number of NaNs in observed (HAI_6): 1607
Number of NaNs in expected (HAI_6): 1612
Symmetric Mean Absolute Percentage Error (SMAPE) for HAI_6: 44.19%


Number of NaNs in observed (READM_30_HOSP_WIDE): 293
Number of NaNs in expected (READM_30_HOSP_WIDE): 291
Symmetric Mean Absolute Percentage Error (SMAPE) for READM_30_HOSP_WIDE: 0.00%


Number of NaNs in observed (READM_30_HIP_KNEE): 2535
Number of NaNs in expected (READM_30_HIP_KNEE): 2535
Symmetric Mean Absolute Percentage Error (SMAPE) for READM_30_HIP_KNEE: 0.00%


Number of NaNs in observed (EDAC_30_HF): 1480
Number of NaNs in expected (EDAC_30_HF): 1481
Symmetric Mean Absolute Percentage Error (SMAPE) for EDAC_30_HF: 0.00%


Number of NaNs in observed (READM_30_COPD): 1986
Number of NaNs in expected (READM_30_COPD): 1984
Symmetric Mean Absolute Percentage Error (SMAPE) for READM_30_COPD: 0.00%


Number of NaNs in observed (EDAC_30_AMI): 3089
Number of NaNs in expected (EDAC_30_AMI): 3089
Symmetric Mean Absolute Percentage Error (SMAPE) for EDAC_30_AMI: 0.00%


Number of NaNs in observed (EDAC_30_PN): 1091
Number of NaNs in expected (EDAC_30_PN): 1091
Symmetric Mean Absolute Percentage Error (SMAPE) for EDAC_30_PN: 0.00%


Number of NaNs in observed (MORT_30_STK): 2481
Number of NaNs in expected (MORT_30_STK): 2481
Symmetric Mean Absolute Percentage Error (SMAPE) for MORT_30_STK: 0.00%


Number of NaNs in observed (MORT_30_PN): 1091
Number of NaNs in expected (MORT_30_PN): 1091
Symmetric Mean Absolute Percentage Error (SMAPE) for MORT_30_PN: 0.00%


Number of NaNs in observed (MORT_30_HF): 1548
Number of NaNs in expected (MORT_30_HF): 1549
Symmetric Mean Absolute Percentage Error (SMAPE) for MORT_30_HF: 0.00%


Number of NaNs in observed (MORT_30_COPD): 2037
Number of NaNs in expected (MORT_30_COPD): 2035
Symmetric Mean Absolute Percentage Error (SMAPE) for MORT_30_COPD: 0.00%


Number of NaNs in observed (MORT_30_AMI): 2661
Number of NaNs in expected (MORT_30_AMI): 2661
Symmetric Mean Absolute Percentage Error (SMAPE) for MORT_30_AMI: 0.00%


Number of NaNs in observed (COMP_HIP_KNEE): 2515
Number of NaNs in expected (COMP_HIP_KNEE): 2515
Symmetric Mean Absolute Percentage Error (SMAPE) for COMP_HIP_KNEE: 0.00%


Number of NaNs in observed (OP_3B): 4250
Number of NaNs in expected (OP_3B): 4237
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_3B: 11.66%


Number of NaNs in observed (OP_8): 3731
Number of NaNs in expected (OP_8): 3731
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_8: 0.00%


Number of NaNs in observed (OP_10): 679
Number of NaNs in expected (OP_10): 681
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_10: 0.00%


Number of NaNs in observed (OP_13): 2713
Number of NaNs in expected (OP_13): 2714
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_13: 0.00%


Number of NaNs in observed (OP_18B): 548
Number of NaNs in expected (OP_18B): 548
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_18B: 4.66%


Number of NaNs in observed (OP_22): 833
Number of NaNs in expected (OP_22): 682
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_22: 39.22%


Number of NaNs in observed (OP_23): 3137
Number of NaNs in expected (OP_23): 3084
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_23: 14.39%


Number of NaNs in observed (OP_29): 1768
Number of NaNs in expected (OP_29): 1696
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_29: 8.51%


Number of NaNs in observed (PSI_4_SURG_COMP): 3177
Number of NaNs in expected (PSI_4_SURG_COMP): 2995
Symmetric Mean Absolute Percentage Error (SMAPE) for PSI_4_SURG_COMP: 16.08%


Number of NaNs in observed (PSI_90_SAFETY): 1590
Number of NaNs in expected (PSI_90_SAFETY): 1594
Symmetric Mean Absolute Percentage Error (SMAPE) for PSI_90_SAFETY: 8.57%


Number of NaNs in observed (IMM_3): 454
Number of NaNs in expected (IMM_3): 345
Symmetric Mean Absolute Percentage Error (SMAPE) for IMM_3: 12.17%


Number of NaNs in observed (HCP_COVID_19): 889
Number of NaNs in expected (HCP_COVID_19): 825
Symmetric Mean Absolute Percentage Error (SMAPE) for HCP_COVID_19: 3.40%


Number of NaNs in observed (PC_01): 2268
Number of NaNs in expected (PC_01): 2289
Symmetric Mean Absolute Percentage Error (SMAPE) for PC_01: 56.13%


Number of NaNs in observed (SEP_1): 1454
Number of NaNs in expected (SEP_1): 1425
Symmetric Mean Absolute Percentage Error (SMAPE) for SEP_1: 10.98%


Number of NaNs in observed (H_COMP_1_STAR_RATING): 1379
Number of NaNs in expected (H_COMP_1_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_COMP_1_STAR_RATING: 9.05%


Number of NaNs in observed (H_COMP_2_STAR_RATING): 1379
Number of NaNs in expected (H_COMP_2_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_COMP_2_STAR_RATING: 7.86%


Number of NaNs in observed (H_COMP_3_STAR_RATING): 1379
Number of NaNs in expected (H_COMP_3_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_COMP_3_STAR_RATING: 8.88%


Number of NaNs in observed (H_COMP_5_STAR_RATING): 1379
Number of NaNs in expected (H_COMP_5_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_COMP_5_STAR_RATING: 11.61%


Number of NaNs in observed (H_COMP_6_STAR_RATING): 1379
Number of NaNs in expected (H_COMP_6_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_COMP_6_STAR_RATING: 9.14%


Number of NaNs in observed (H_COMP_7_STAR_RATING): 1379
Number of NaNs in expected (H_COMP_7_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_COMP_7_STAR_RATING: 10.50%


Number of NaNs in observed (H_GLOB_STAR_RATING): 1379
Number of NaNs in expected (H_GLOB_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_GLOB_STAR_RATING: 7.45%


Number of NaNs in observed (H_INDI_STAR_RATING): 1379
Number of NaNs in expected (H_INDI_STAR_RATING): 1375
Symmetric Mean Absolute Percentage Error (SMAPE) for H_INDI_STAR_RATING: 8.48%


Number of NaNs in observed (MORT_30_CABG): 3721
Number of NaNs in expected (MORT_30_CABG): 3721
Symmetric Mean Absolute Percentage Error (SMAPE) for MORT_30_CABG: 0.00%


Number of NaNs in observed (READM_30_CABG): 3727
Number of NaNs in expected (READM_30_CABG): 3727
Symmetric Mean Absolute Percentage Error (SMAPE) for READM_30_CABG: 0.00%


Number of NaNs in observed (OP_32): 1353
Number of NaNs in expected (OP_32): 1430
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_32: 8.20%


Number of NaNs in observed (OP_35_ADM): 3064
Number of NaNs in expected (OP_35_ADM): 3092
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_35_ADM: 10.94%


Number of NaNs in observed (OP_35_ED): 3064
Number of NaNs in expected (OP_35_ED): 3092
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_35_ED: 12.28%


Number of NaNs in observed (OP_36): 1842
Number of NaNs in expected (OP_36): 1782
Symmetric Mean Absolute Percentage Error (SMAPE) for OP_36: 17.24%

In [10]:
compare_dfs(df_2024, nov_df, 'Nov 2023', nov_dates, actual_dates)

NameError: name 'compare_dfs' is not defined

In [11]:
compare_dfs(df_2024, jan_df, 'Jan 2024', jan_dates, actual_dates)

NameError: name 'compare_dfs' is not defined

In [12]:
df_2024.head()

,PROVIDER_ID,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,OP_3B,OP_8,OP_10,OP_13,OP_18B,OP_22,OP_23,OP_29,PSI_4_SURG_COMP,PSI_90_SAFETY,IMM_3,HCP_COVID_19,PC_01,SEP_1,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,MORT_30_CABG,READM_30_CABG,OP_32,OP_35_ADM,OP_35_ED,OP_36
0,010001,0.938,0.363,1.335,NaN,0.965,0.507,0.142,0.038,23.4,0.190,-15.4,23.6,0.148,0.180,0.089,0.088,0.120,0.027,NaN,0.380,0.061,0.028,214.0,0.05,NaN,0.47,184.68,1.21,0.95,0.836,0.00,0.65,3.0,3.0,3.0,3.0,4.0,4.0,3.5,3.5,0.041,0.105,12.9,11.9,4.9,1.1
1,010005,2.514,0.995,0.762,NaN,0.541,0.497,0.128,0.034,22.1,0.166,NaN,-6.2,0.153,0.233,0.149,0.099,0.136,0.023,57.0,0.477,0.120,0.042,145.0,0.03,0.58,0.96,183.49,0.97,0.80,0.807,0.02,0.69,3.0,4.0,1.0,3.0,4.0,3.0,3.0,3.0,NaN,NaN,14.2,7.9,5.5,1.9
2,010006,0.172,0.358,0.000,NaN,1.514,0.072,0.134,0.053,-4.7,0.176,28.1,-0.4,0.172,0.195,0.125,0.099,0.165,0.046,NaN,0.462,0.101,0.045,168.0,0.01,0.75,0.85,173.63,1.17,0.67,0.796,0.04,0.57,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.5,0.036,0.124,12.1,NaN,NaN,1.4
3,010007,NaN,NaN,NaN,NaN,NaN,0.376,0.157,0.042,-1.9,0.200,NaN,-9.4,NaN,0.285,0.125,0.137,NaN,NaN,NaN,NaN,0.034,NaN,132.0,0.04,NaN,0.23,NaN,0.95,0.53,0.601,NaN,0.93,3.0,5.0,4.0,3.0,3.0,3.0,3.5,3.0,NaN,NaN,13.4,NaN,NaN,1.2
4,010008,NaN,NaN,NaN,NaN,NaN,NaN,0.148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,116.0,0.00,NaN,0.67,NaN,NaN,0.45,0.797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9,NaN,NaN,NaN

In [13]:
jan_df.head()

,PROVIDER_ID,HAI_1,HAI_2,HAI_3,HAI_4,HAI_5,HAI_6,READM_30_HOSP_WIDE,READM_30_HIP_KNEE,EDAC_30_HF,READM_30_COPD,EDAC_30_AMI,EDAC_30_PN,MORT_30_STK,MORT_30_PN,MORT_30_HF,MORT_30_COPD,MORT_30_AMI,COMP_HIP_KNEE,OP_3B,OP_8,OP_10,OP_13,OP_18B,OP_22,OP_23,OP_29,PSI_4_SURG_COMP,PSI_90_SAFETY,IMM_3,HCP_COVID_19,PC_01,SEP_1,H_COMP_1_STAR_RATING,H_COMP_2_STAR_RATING,H_COMP_3_STAR_RATING,H_COMP_5_STAR_RATING,H_COMP_6_STAR_RATING,H_COMP_7_STAR_RATING,H_GLOB_STAR_RATING,H_INDI_STAR_RATING,MORT_30_CABG,READM_30_CABG,OP_32,OP_35_ADM,OP_35_ED,OP_36
0,010001,0.938,0.363,1.335,NaN,0.965,0.507,0.142,0.038,23.4,0.190,-15.4,23.6,0.148,0.180,0.089,0.088,0.120,0.027,NaN,0.380,0.061,0.028,214.0,0.05,NaN,0.47,184.68,1.21,0.95,0.836,0.00,0.65,3.0,3.0,3.0,3.0,4.0,4.0,3.5,3.5,0.041,0.105,12.9,11.9,4.9,1.1
1,010005,2.514,0.995,0.762,NaN,0.541,0.497,0.128,0.034,22.1,0.166,NaN,-6.2,0.153,0.233,0.149,0.099,0.136,0.023,57.0,0.477,0.120,0.042,145.0,0.03,0.58,0.96,183.49,0.97,0.80,0.807,0.02,0.69,3.0,4.0,1.0,3.0,4.0,3.0,3.0,3.0,NaN,NaN,14.2,7.9,5.5,1.9
2,010006,0.172,0.358,0.000,NaN,1.514,0.072,0.134,0.053,-4.7,0.176,28.1,-0.4,0.172,0.195,0.125,0.099,0.165,0.046,NaN,0.462,0.101,0.045,168.0,0.01,0.75,0.85,173.63,1.17,0.67,0.796,0.04,0.57,2.0,3.0,2.0,2.0,3.0,2.0,2.0,2.5,0.036,0.124,12.1,NaN,NaN,1.4
3,010007,NaN,NaN,NaN,NaN,NaN,0.376,0.157,0.042,-1.9,0.200,NaN,-9.4,NaN,0.285,0.125,0.137,NaN,NaN,NaN,NaN,0.034,NaN,132.0,0.04,NaN,0.23,NaN,0.95,0.53,0.601,NaN,0.93,3.0,5.0,4.0,3.0,3.0,3.0,3.5,3.0,NaN,NaN,13.4,NaN,NaN,1.2
4,010008,NaN,NaN,NaN,NaN,NaN,NaN,0.148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,116.0,0.00,NaN,0.67,NaN,NaN,0.45,0.797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9,NaN,NaN,NaN